import Clean.Ironwood.Specs.Types
import Clean.Ironwood.Specs.Bitrange
import Clean.Ironwood.Specs.Pallas
import Clean.Ironwood.Specs.PallasCert
import Clean.Ironwood.Specs.Sinsemilla
import Clean.Ironwood.Specs.SinsemillaBreak
import Clean.Ironwood.Specs.SinsemillaGenerators
import Clean.Ironwood.Utilities.RunningSum
import Clean.Ironwood.Ecc.Defs
import Clean.Ironwood.Ecc.DoubleAndAdd
import Clean.Ironwood.Ecc.AddTheorems
import Clean.Ironwood.Ecc.AddIncompleteTheorems
import Clean.Ironwood.Ecc.MulTheorems
import Clean.Ironwood.Ecc.MulIncompleteTheorems
import Clean.Ironwood.Ecc.MulCompleteTheorems
import Clean.Ironwood.Ecc.MulOverflowTheorems
import Clean.Ironwood.Ecc.MulAssignTheorems
import Clean.Ironwood.Ecc.MulFixed.Theorems
import Clean.Ironwood.Ecc.MulFixed.BaseFieldElemTheorems
import Clean.Ironwood.Ecc.MulFixed.ShortTheorems
import Clean.Ironwood.Ecc.MulFixed.CertCheck
import Clean.Ironwood.Ecc.MulFixed.Certs.NullifierK
import Clean.Ironwood.Ecc.MulFixed.Certs.ValueCommitR
import Clean.Ironwood.Ecc.MulFixed.Certs.SpendAuthG
import Clean.Ironwood.Ecc.MulFixed.Certs.CommitIvkR
import Clean.Ironwood.Ecc.MulFixed.Certs.NoteCommitR
import Clean.Ironwood.Ecc.MulFixed.Certs.ValueCommitV
import Clean.Ironwood.Sinsemilla.HVec
import Clean.Ironwood.Sinsemilla.ChipTheorems
import Clean.Ironwood.Sinsemilla.ChainTheorems
import Clean.Ironwood.Sinsemilla.CommitDomainTheorems
import Clean.Ironwood.Poseidon.Constants
import Clean.Ironwood.Poseidon.Pow5Theorems
import Clean.Ironwood.Poseidon.SpongeTheorems
import Clean.Ironwood.Poseidon.HashTheorems
import Clean.Ironwood.NoteCommit.CanonicityTheorems
import Clean.Ironwood.NoteCommit.DecomposeTheorems
import Clean.Ironwood.NoteCommit.MainTheorems
import Clean.Ironwood.CommitIvk.GateTheorems
import Clean.Ironwood.CommitIvk.ChunkTheorems
import Clean.Ironwood.CommitIvk.MainTheorems
import Clean.Ironwood.Ecc.Basic
import Clean.Ironwood.Ecc.WitnessPoint
import Clean.Ironwood.Ecc.AddIncomplete
import Clean.Ironwood.Ecc.Add
import Clean.Ironwood.Ecc.MulIncomplete
import Clean.Ironwood.Ecc.MulComplete
import Clean.Ironwood.Ecc.MulOverflow
import Clean.Ironwood.Ecc.Mul
import Clean.Ironwood.Ecc.MulFixed
import Clean.Ironwood.Ecc.MulFixed.BaseFieldElem
import Clean.Ironwood.Ecc.MulFixed.FullWidth
import Clean.Ironwood.Ecc.MulFixed.Short
import Clean.Ironwood.Utilities.LookupRangeCheck
import Clean.Ironwood.CommitIvk.Gate
import Clean.Ironwood.CommitIvk.Bundle
import Clean.Ironwood.CommitIvk.Composite
import Clean.Ironwood.NoteCommit.Gates
import Clean.Ironwood.NoteCommit.Decompose
import Clean.Ironwood.NoteCommit.Canonicity
import Clean.Ironwood.NoteCommit.Composites
import Clean.Ironwood.NoteCommit.YComposite
import Clean.Ironwood.NoteCommit.Main
import Clean.Ironwood.NoteCommit.MainBundle
import Clean.Ironwood.CommitIvk.Main
import Clean.Ironwood.CommitIvk.MainBundle
import Clean.Ironwood.Utilities.AddChip
import Clean.Ironwood.Poseidon.Pow5
import Clean.Ironwood.Poseidon.Rounds
import Clean.Ironwood.Poseidon.Permute
import Clean.Ironwood.Poseidon.Hash
import Clean.Ironwood.Sinsemilla.Basic
import Clean.Ironwood.Sinsemilla.HashPiece
import Clean.Ironwood.Sinsemilla.Chain
import Clean.Ironwood.Action.DeriveNullifier
import Clean.Ironwood.Action.ValueCommit
import Clean.Ironwood.Action.SpendAuthority
import Clean.Ironwood.Action.AddressIntegrity
import Clean.Ironwood.Ecc.Chip
import Clean.Ironwood.Action.Circuit
import Clean.Ironwood.Action.Bundle
import Clean.Ironwood.Action.RealBases
import Clean.Ironwood.Action.TopLevel

/-!
# Ironwood circuits

Aggregator for the Ironwood (halo2-native) circuit modules. Ironwood is kept separate
from the main `Clean` library export and can be built with `lake build Zcash`.
-/
