-- This file imports all test modules
import Clean.Utils.Test.TestDecomposeProvableStruct
import Clean.Utils.Test.TestSplitProvableStructEq
import Clean.Utils.Test.TestCircuitProofStart
import Clean.Utils.Test.TestSimplifyProvableStructEval
import Clean.Utils.Test.TestWitgenEvalProjection
import Clean.Utils.Test.TestElaborateCircuit
import Clean.Utils.Test.TestCircuitStructDeriving
import Clean.Utils.Test.TestMixedCircuitType
import Clean.Utils.Test.TestLookup
import Clean.Utils.Test.SimpMatchRegression
import Clean.Halo2.Tests.TestProvableTypeSimp
import Clean.Halo2.Tests.TestCircuitTypeDeriving
import Clean.Halo2.Tests.TestSubcircuit
import Clean.Halo2.Tests.TestRawBind
import Clean.Halo2.Tests.TestLayouterSubcircuit
import Clean.Halo2.Tests.TestSubcircuitRw
import Clean.Halo2.Tests.TestAbstractOutputs
import Clean.Halo2.Tests.TestLoops
import Clean.Halo2.Tests.TestContractBridges
import Clean.Halo2.Tests.TestLookupMembership
import Clean.Halo2.Tests.TestProofStart
import Clean.Halo2.Tests.TestTupleLookup
import Clean.Halo2.Tests.TestSelectorFree
import Clean.Halo2.Tests.TestWitnessSupport
import Clean.Ironwood.Tests.TestVkMatchAdd
import Clean.Ironwood.Tests.TestVkLayoutAdd
import Clean.Ironwood.Tests.TestVkMatchMul
import Clean.Ironwood.Tests.TestVkLayoutMul
import Clean.Ironwood.Tests.TestVkMatchAction
import Clean.Ironwood.Tests.TestVkLayoutAction
import Clean.Ironwood.Tests.TestVkLayoutActionBase
